import = ["~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"]

[env]
TERM = "alacritty"

[font]
size = 10.0

[font.bold]
family = "JetBrains Mono NL"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono NL"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono NL"
style = "Italic"

[font.normal]
family = "JetBrains Mono NL"
style = "Regular"

[scrolling]
history = 10000

[window]
opacity = 0.5
